name: 'spacex_analytics'
version: '1.0.0'
config-version: 2
profile: 'spacex_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  spacex_analytics:
    # Silver layer - cleaned and parsed data
    silver:
      +materialized: view
      +schema: silver  # This creates views in the 'silver' schema
      # +pre-hook: "CREATE SCHEMA IF NOT EXISTS silver"
    # Gold layer - business analytics
    gold:
      +materialized: table
      +schema: gold    # This creates tables in the 'gold' schema
      # +pre-hook: "CREATE SCHEMA IF NOT EXISTS gold"


tests:
  spacex_analytics:
    +severity: warn
